FROM postgres:15-alpine

RUN apk add --no-cache openssl

COPY scripts/postgres-ssl-entrypoint.sh /usr/local/bin/postgres-ssl-entrypoint.sh
RUN chmod +x /usr/local/bin/postgres-ssl-entrypoint.sh

ENTRYPOINT ["postgres-ssl-entrypoint.sh"]
CMD ["postgres"]
